# Generated by Django 4.1.7 on 2023-04-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
